name: Barista preview

on:
  pull_request:
    branches:
      - master

jobs:
  deploy:
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install
        run: npm ci

      - name: Build Barista Design System
        run: |
          npm run nx run workspace:build
          npm run nx run barista-tools:build
          npm run nx run barista-tools:execute
          npm run nx run barista-design-system:static-pages:production

      - name: Vercel Deployment
        id: vercel-action
        uses: amondnet/vercel-action@v19.0.1+4
        with:
          vercel-token: ${{ secrets.ZEIT_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-args:
            '--scope dynatrace-oss --confirm
            ./dist/apps/barista-design-system/browser'
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}

      - name: Generating Lighthouse Report
        uses: jakejarvis/lighthouse-action@master
        with:
          url: ${{ steps.vercel-action.outputs.preview-url }}

      - name: Save Lighthouse Audit
        uses: actions/upload-artifact@master
        with:
          name: barista-audit
          path: './report'
